NumPy is an open source library available in Python that aids in mathematical, scientific, engineering, and data science programming.
NumPy is a programming language that deals with multi-dimensional arrays and matrices. Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists.

On top of the arrays and matrices, NumPy supports a large number of mathematical operations

NumPy — это библиотека с открытым исходным кодом для Python, которая используется в математическом, научном, инженерном программировании и анализе данных.

NumPy работает с многомерными массивами и матрицами.

Массивы похожи на списки в Python, однако есть важное отличие: все элементы массива должны быть одного типа, обычно числового (например, float или int).

Массивы позволяют выполнять операции с большими объёмами числовых данных очень быстро и, как правило, являются гораздо более эффективными, чем обычные списки Python.

Помимо работы с массивами и матрицами, NumPy поддерживает большое количество математических операций.

# Importing

In [2]:
# import numpy
import numpy as np

In [3]:
# !pip install numpy

In [4]:
np.__version__

'1.26.4'

To display NumPy's built-in documentation, you can use this:

Чтобы отобразить встроенную документацию NumPy, можно использовать следующий способ:

In [ ]:
np?

# Python List vs Numpy Array
Because of Python's dynamic typing, we can create heterogeneous lists:

Благодаря динамической типизации Python мы можем создавать неоднородные (гетерогенные) списки:

In [5]:
L = [True, "2", 3.0, 4]
[type(item) for item in L]

[bool, str, float, int]

This flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information–that is, each item is a complete Python object. In the special case that all variables are of the same type, much of this information is redundant: it can be much more efficient to store data in a fixed-type array. The difference between a dynamic-type list and a fixed-type (NumPy-style) array is illustrated in the following figure:


Эта гибкость имеет свою цену: чтобы поддерживать такие гибкие типы, каждый элемент списка должен содержать собственную информацию о типе, счётчик ссылок и другие служебные данные — то есть каждый элемент является полноценным объектом Python.

В частном случае, когда все элементы имеют один и тот же тип, большая часть этой информации оказывается избыточной. В такой ситуации гораздо эффективнее хранить данные в массиве с фиксированным типом.

Различие между списком с динамической типизацией и массивом с фиксированным типом (в стиле NumPy) показано на следующем рисунке:


![alt text](https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png)

At the implementation level, the array essentially contains a single pointer to one contiguous block of data. The Python list, on the other hand, contains a pointer to a block of pointers, each of which in turn points to a full Python object like the Python integer we saw earlier. Again, the advantage of the list is flexibility: because each list element is a full structure containing both data and type information, the list can be filled with data of any desired type. Fixed-type NumPy-style arrays lack this flexibility, but are much more efficient for storing and manipulating data.


На уровне реализации массив по сути содержит один указатель на непрерывный блок данных в памяти.

Список Python, напротив, содержит указатель на блок указателей, каждый из которых, в свою очередь, указывает на полноценный объект Python (например, целое число Python, которое мы рассматривали ранее).

Преимущество списка заключается в его гибкости: поскольку каждый элемент списка представляет собой полноценную структуру, содержащую как данные, так и информацию о типе, список может хранить данные любого типа.

Массивы с фиксированным типом (в стиле NumPy) лишены такой гибкости, однако они значительно более эффективны с точки зрения хранения и обработки данных.

# NumPy Arrays
The central feature of NumPy is the array object class. Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists.

Центральным элементом NumPy является класс объекта array (массив).
Массивы похожи на списки в Python, однако существует важное отличие: все элементы массива должны быть одного типа, обычно числового, например float или int.
Массивы позволяют выполнять операции с большими объёмами числовых данных очень быстро и, как правило, являются значительно более эффективными по сравнению со списками Python.

Creating Arrays

In [6]:
# Manual construction of 1-D arrays
one_D = np.array([0, 1, 2, 3])
print(one_D)
type(one_D)

[0 1 2 3]


numpy.ndarray

In [7]:
# Check number of array dimensions
one_D.ndim

1

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

В отличие от списков Python, NumPy ограничен массивами, элементы которых должны быть одного и того же типа. Если типы не совпадают, NumPy по возможности выполняет приведение типов (upcasting) — например, целые числа автоматически преобразуются в числа с плавающей точкой:

In [8]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

If we want to explicitly set the data type of the resulting array, we can use the **dtype** keyword:

Если мы хотим явно задать тип данных создаваемого массива, можно использовать параметр **dtype**:

In [9]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [10]:
# Manual construction of 2 and 3-D arrays
two_D = np.array([[0, 1, 2],
                  [3, 4, 5]])
print(two_D.ndim)
three_D = np.array([
                    [[1],
                     [2]],
                    [[3],
                     [4]]
                    ])
print(three_D.ndim)

2
3


In [11]:
# Shape of array
print(two_D.shape)
print(three_D.shape)
print(three_D)
# print(type(three_D))

(2, 3)
(2, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]]


In [12]:
# returns the size of the first dimension
len(two_D)

2

## Functions for creating arrays
In practice, we rarely enter items one by one

##Функции для создания массивов
На практике мы редко вводим элементы по одному.

In [13]:
np.zeros(5)
# np.zeros((2,2))

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [15]:
np.ones((2, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.full((2, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

###### Evenly spaced

In [17]:
np.arange(10) # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1, 9, 2) # start, end (exclusive), step

array([1, 3, 5, 7])

###### By number of points

In [19]:
np.linspace(0, 1, 6)  # start, end, num-points

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
np.linspace(0, 1, 6, endpoint=False)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333])

In [21]:
np.ones((3, 3))  # reminder: (3, 3) is a tuple

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
# Create an uninitialized array of 2x3 size
np.empty([3, 3])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random numbers

In [26]:
# create a numpy array of 4 uniformly distributed numbers
np.random.rand(4)       # uniform in [0, 1]

array([0.9960676 , 0.43511146, 0.73933053, 0.74008967])

In [27]:
#create a numpy array of 7 normally distributed numbers
np.random.randn(5)      # Gaussian

array([-1.26596762, -1.51559556, -0.22884522,  0.25168009, -0.22843737])

In [28]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.37839128, 0.80758918, 0.21677034],
       [0.01253009, 0.11007389, 0.30864197],
       [0.26310938, 0.34106956, 0.336127  ]])

In [29]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.72860998, -0.18411067, -0.36464549],
       [-0.06158434, -0.59398914,  0.29712089],
       [-1.095074  , -0.77784544, -1.90646882]])

In [30]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 5, 3],
       [9, 6, 3],
       [0, 2, 6]])

# NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

# The standard NumPy data types are listed in the following table. Note that when constructing an array, they can be specified using a string:

Стандартные типы данных NumPy

Массивы NumPy содержат значения одного типа, поэтому важно хорошо понимать эти типы и их ограничения. Поскольку NumPy реализован на языке C, типы данных будут знакомы пользователям C, Fortran и других родственных языков.

Стандартные типы данных NumPy приведены в следующей таблице. Обратите внимание, что при создании массива их можно указывать в виде строки:

In [31]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [32]:
# or
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)|
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)|
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)|
| ``int8``      | Byte (-128 to 127)|
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)|
| ``uint8``     | Unsigned integer (0 to 255)|
| ``uint16``    | Unsigned integer (0 to 65535)|
| ``uint32``    | Unsigned integer (0 to 4294967295)|
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)|
| ``float_``    | Shorthand for ``float64``.|
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
| ``complex_``  | Shorthand for ``complex128``.|
| ``complex64`` | Complex number, represented by two 32-bit floats|
| ``complex128``| Complex number, represented by two 64-bit floats|

# NumPy Array Attributes

In [33]:
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x3)

[[[3 2 3 6 8]
  [5 0 4 5 2]
  [4 9 6 5 6]
  [4 6 4 4 8]]

 [[1 0 0 0 2]
  [6 6 1 4 0]
  [0 7 5 0 2]
  [6 8 1 8 5]]

 [[4 8 6 8 0]
  [1 4 8 3 1]
  [6 7 1 6 9]
  [7 1 5 0 6]]]


In [34]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [35]:
print("dtype:", x3.dtype)

dtype: int32


Other attributes include `itemsize`, which lists the size (in bytes) of each array element, and `nbytes`, which lists the total size (in bytes) of the array:

In [36]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In general, we expect that `nbytes` is equal to `itemsize` times `size`.

# Indexing and slicing
The items of an array can be accessed and assigned to the same way as other Python lists.

## Индексация и срезы

К элементам массива можно обращаться и присваивать им значения так же, как и в обычных списках Python.

In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a[0], a[2], a[-1]

(0, 2, 9)

For multidimensional arrays, indexes are tuples of integers.

In [39]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [40]:
a[2, 1] = 77 # third line, second column  (for lists a[2][1])
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 77,  2]])

Keep in mind, that if we attempt to insert a floating-point value to an integer array, the value will be silently truncated.

In [41]:
a[0, 1] =  3.14
a

array([[ 0,  3,  0],
       [ 0,  1,  0],
       [ 0, 77,  2]])

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

`x[start:stop:step]`

## One-dimensional subarrays

In [42]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a[2:9:3] # [start:end:step]

array([2, 5, 8])

Note that the last index is not included

In [44]:
a[:4]

array([0, 1, 2, 3])

In [45]:
a[1:3]

array([1, 2])

In [46]:
a[::2]

array([0, 2, 4, 6, 8])

In [47]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [48]:
a[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

It is possible to combine assignment and slicing

In [49]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [50]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [51]:
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

## Multi-dimensional subarrays
Multi-dimensional slices work in the same way, with multiple slices separated by commas.

In [52]:
x2 = x3[0]
print(x2)

[[3 2 3 6 8]
 [5 0 4 5 2]
 [4 9 6 5 6]
 [4 6 4 4 8]]


In [53]:
x2[:2, :3] # two rows, three columns

array([[3, 2, 3],
       [5, 0, 4]])

In [54]:
x2[:3, ::2]  # all rows, every other column

array([[3, 3, 8],
       [5, 4, 2],
       [4, 6, 6]])

Finally, subarray dimensions can even be reversed together:

In [55]:
x2[::-1, ::-1]

array([[8, 4, 4, 6, 4],
       [6, 5, 6, 9, 4],
       [2, 5, 4, 0, 5],
       [8, 6, 3, 2, 3]])

## Accessing array rows and columns
One commonly needed routine is accessing of single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [56]:
print(x2)

[[3 2 3 6 8]
 [5 0 4 5 2]
 [4 9 6 5 6]
 [4 6 4 4 8]]


In [57]:
print(x2[:, 0])  # first column of x2

[3 5 4 4]


In [58]:
print(x2[0, :])  # first row of x2

[3 2 3 6 8]


In [59]:
print(x2[0])  # equivalent to x2[0, :]

[3 2 3 6 8]


## Subarrays as no-copy views
One important and extremely useful thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.

In [60]:
print(x2)

[[3 2 3 6 8]
 [5 0 4 5 2]
 [4 9 6 5 6]
 [4 6 4 4 8]]


In [61]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 2]
 [5 0]]


Now if we modify this subarray, we'll see that the original array is changed!

In [62]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  2]
 [ 5  0]]


In [63]:
print(x2)

[[99  2  3  6  8]
 [ 5  0  4  5  2]
 [ 4  9  6  5  6]
 [ 4  6  4  4  8]]


In [64]:
# checks if a and b share the same memory block
np.may_share_memory(x2, x2_sub)

True

### Creating copies of arrays
Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:

In [65]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  2]
 [ 5  0]]


In [66]:
x2_sub_copy[0, 0] = 777
print(x2_sub_copy)

[[777   2]
 [  5   0]]


In [67]:
# checks if a and b share the same memory block
np.may_share_memory(x2, x2_sub_copy)

False

In [68]:
print(x2)

[[99  2  3  6  8]
 [ 5  0  4  5  2]
 [ 4  9  6  5  6]
 [ 4  6  4  4  8]]


# Modifying Arrays

## Reshaping Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following:

In [69]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, **the size of the initial array must match the size of the reshaped array**. Where possible, the reshape method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the reshape method, or more easily done by making use of the `newaxis` keyword within a slice operation:

In [70]:
x = np.array([1, 2, 3])
print(x.shape)

# row vector via reshape
x = x.reshape((1, 3))
print(x)
print(x.shape)

(3,)
[[1 2 3]]
(1, 3)


In [71]:
a = np.array([[1,2,3],
              [2,3,4]])

a = a.flatten()
print(a)
a= a.reshape((3, 2))
print(a)

[1 2 3 2 3 4]
[[1 2]
 [3 2]
 [3 4]]


In [72]:
x = np.array([1, 2, 3])

# row vector via newaxis
x = x[np.newaxis, :]
print(x.shape)

(1, 3)


In [73]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [74]:
x = np.array([1, 2, 3])

# column vector via newaxis
x[:, np.newaxis].shape

(3, 1)

## Resizing
Size of an array can be changed with ndarray.resize.

In [75]:
a = np.arange(4)
print(a)
a.resize((8,))
print(a)

[0 1 2 3]
[0 1 2 3 0 0 0 0]


## Concatenating Arrays
Concatenation, or joining of two arrays in **NumPy**, is primarily accomplished using the routines `np.concatenate`, `np.vstack`, and `np.hstack`.

`np.concatenate` takes a tuple or list of arrays as its first argument, as we can see here:

In [76]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [77]:
# concatenate more than two arrays
z = [99, 88, 77]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 88 77]


It can be also used for 2-D arrays:

In [78]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [79]:
# concatenate along the first axis
# if the axis property is not set, defaults to axis = 0
np.concatenate([grid, grid], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [80]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the `np.vstack` (vertical stack) and `np.hstack` (horizontal stack) functions:

In [81]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [82]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similary, `np.dstack` will stack arrays along the third axis.


## Splitting Arrays
The opposite of concatenation is splitting, which is implemented by the functions `np.split`, `np.hsplit`, and `np.vsplit`. For each of these, we can pass a list of indices giving the split points:

In [83]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [84]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [86]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [141]:
import numpy as np

print("===== NumPy Exercises (Basic & Mid Level) =====")

# ===== BASIC LEVEL =====

# 1. Create a NumPy array with values from 0 to 9.

# 2. Create the array [1, 2, 3, 4] with data type float.

# 3. Create:
#    a) an array of 10 zeros
#    b) an array of 10 ones

# 4. Create an array of integers from 10 to 50 (inclusive).

# 5. Create an array of even numbers from 0 to 20 (inclusive).

# 6. Create an array with values 1 to 9 and reshape it into a 3×3 matrix.

# 7. Given A = np.array([10, 20, 30, 40, 50]):
#    a) get the first element
#    b) get the last element
#    c) get elements with indices 1 to 3

# 8. Given B = np.array([1, 2, 3, 4]):
#    a) multiply the array by 2
#    b) add 5 to each element


# ===== MID LEVEL =====

# 9. Generate 20 random integers in the range [1, 100].
#    Print only the values greater than 50.

# 10. Generate 15 random integers.
#     Compute:
#     a) mean
#     b) minimum
#     c) maximum
#     d) standard deviation

# 11. Create a 4×4 matrix with values from 1 to 16.
#     Extract:
#     a) the 2nd row
#     b) the 3rd column
#     c) the central 2×2 block

# 12. Add the arrays [1, 2, 3] and [10, 20, 30] using broadcasting.

# 13. Given u = [1, 2, 3] and v = [4, 5, 6]:
#     a) compute the elementwise product
#     b) compute the dot product

# 14. Generate 10 random numbers.
#     Normalize them so that all values lie in the range [0, 1].

# 15. Generate 15 random integers.
#     Replace all values less than 30 with 0.

===== NumPy Exercises (Basic & Mid Level) =====


##### 1. Create a NumPy array with values from 0 to 9.

In [89]:
numbers = np.arange(10)
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 2. Create the array [1, 2, 3, 4] with data type float.

In [93]:
numbers = np.arange(4, dtype=float)
numbers

array([0., 1., 2., 3.])

##### 3. Create:  a) an array of 10 zeros   b) an array of 10 ones

In [96]:
numbers = np.zeros(10, dtype=int)
numbers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
numbers = np.ones(10, dtype=int)
numbers 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

##### 4. Create an array of integers from 10 to 50 (inclusive).

In [101]:
numbers = np.arange(10, 51)
numbers

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

##### 5. Create an array of even numbers from 0 to 20 (inclusive).

In [104]:
numbers = np.arange(2, 21, 2 )
numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

##### 6. Create an array with values 1 to 9 and reshape it into a 3×3 matrix.

In [ ]:
numbers = np.arange(1,10).reshape(3,3)
numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### 7. Given A = np.array([10, 20, 30, 40, 50]):  a) get the first element  b) get the last element  c) get elements with indices 1 to 3


In [119]:
numbers = np.arange(10,60, 10)
print(numbers[0])
print(numbers[-1])
print(numbers[1:4])

10
50
[20 30 40]


##### 8. Given B = np.array([1, 2, 3, 4]):  a) multiply the array by 2  b) add 5 to each element

In [121]:
numbers = np.arange(1,5)
print(numbers * 2)
print(numbers + 5)

[2 4 6 8]
[6 7 8 9]


##### 9. Generate 20 random integers in the range [1, 100].  Print only the values greater than 50.

In [126]:
numbers = np.random.randint(1, 101, size=20)
numbers[numbers > 50]

array([61, 70, 61, 73, 96, 95, 95, 70, 72])

##### 10. Generate 15 random integers.  Compute:  a) mean  b) minimum  c) maximum  d) standard deviation

In [133]:
numbers = np.random.randint(0, 100, size= 15)
print(numbers)
print(numbers.mean())
print(numbers.min())
print(numbers.max())
print(numbers.std())

[99 83 86 45 40 90 15 52 54 13 22 32 99 37 63]
55.333333333333336
13
99
28.91981250899728


##### 11. Create a 4×4 matrix with values from 1 to 16.  Extract:  a) the 2nd row  b) the 3rd column  c) the central 2×2 block

In [134]:
matrix = np.arange(1, 17).reshape(4, 4)
print(matrix)

# the 2nd row 
second_row = matrix[1, :]
print(second_row)

# the 3rd column
third_column = matrix[:, 2]
print(third_column)

# the central 2x2 block
central_block = matrix[1:3, 1:3]
print(central_block)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8]
[ 3  7 11 15]
[[ 6  7]
 [10 11]]


##### 12. Add the arrays [1, 2, 3] and [10, 20, 30] using broadcasting.

In [136]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

new = a + b
new

array([11, 22, 33])

##### 13. Given u = [1, 2, 3] and v = [4, 5, 6]:  a) compute the elementwise product  b) compute the dot product

In [137]:
u = [1, 2, 3] 
v = [4, 5, 6]
print(np.multiply(u, v))
print(np.dot(u, v))

[ 4 10 18]
32


##### 14. Generate 10 random numbers. Normalize them so that all values lie in the range [0, 1].


In [ ]:
numbers = np.random.randint(0, 100, size= 10)
print(numbers)
normalized_data = (numbers - np.min(numbers)) / (np.max(numbers) - np.min(numbers))
print(normalized_data)



[ 4 15 44 92 62 68 35 98 57 23]
[0.         0.11702128 0.42553191 0.93617021 0.61702128 0.68085106
 0.32978723 1.         0.56382979 0.20212766]


##### 15. Generate 15 random integers. Replace all values less than 30 with 0.

In [142]:
numbers = np.random.randint(0, 100, size= 15)
numbers[numbers > 30] = 0

numbers 

array([ 0,  0,  0,  0, 28,  0,  0,  0,  0,  0,  6, 22, 21, 12,  1])

# Computation on NumPy Arrays: Universal Functions
The reasons that **NumPy** is so important in the Python data science world is that  it provides an easy and flexible interface to optimized computation with arrays of data.

Computation on NumPy arrays can be very fast, or it can be very slow. The key to making it fast is to use `vectorized operations`, generally implemented through NumPy's universal functions (**ufuncs**).

## Вычисления с массивами NumPy: универсальные функции

Причина, по которой NumPy играет столь важную роль в мире анализа данных на Python, заключается в том, что он предоставляет простой и гибкий интерфейс для оптимизированных вычислений с массивами данных.

Вычисления с массивами NumPy могут выполняться как очень быстро, так и очень медленно. Ключ к высокой производительности — использование векторизованных операций, которые обычно реализуются через универсальные функции NumPy (ufuncs).

### The Slowness of Loops
The slowness of Python generally manifests itself in situations where many small operations are being repeated – for instance looping over arrays to operate on each element. For example, imagine we have an array of values and we'd like to compute the reciprocal of each. A straightforward approach might look like this:

In [ ]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.33333333, 0.125     , 0.16666667, 0.5       , 0.125     ])

In [ ]:
big_array = np.random.randint(1, 100, size=1000000)
%time compute_reciprocals(big_array)

CPU times: user 2.32 s, sys: 0 ns, total: 2.32 s
Wall time: 2.32 s


array([0.01315789, 0.02222222, 0.03703704, ..., 0.01162791, 0.01851852,
       0.01388889])

 Each time the reciprocal is computed, Python first examines the object's type and does a dynamic lookup of the correct function to use for that type.

We saw how slow is calculating reciprocal of milion elements. For many types of operations NumPy provides a convenient interface into just this kind of statically typed, compiled routine. This is known as a **vectorized** operation.

This can be accomplished by simply performing an operation on the array, which will then be applied to each element. This vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to much faster execution.

If we compare results of below two examples we see that they are exactly same:

In [ ]:
%time (1.0 / big_array)

CPU times: user 3.13 ms, sys: 4.93 ms, total: 8.06 ms
Wall time: 11.8 ms


array([0.01315789, 0.02222222, 0.03703704, ..., 0.01162791, 0.01851852,
       0.01388889])

Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated operations on values in NumPy arrays. Ufuncs are extremely flexible – before we saw an operation between a scalar and an array, but we can also operate between two arrays:

In [ ]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

And ufunc operations are not limited to one-dimensional arrays–they can also act on multi-dimensional arrays as well:

In [ ]:
x = np.arange(9).reshape((3, 3))
print(x)
2 ** x

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

# Array arithmetic
NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators. The standard addition, subtraction, multiplication, and division can all be used:

In [ ]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


There is also a unary ufunc for negation, and a ** operator for exponentiation, and a % operator for modulus:

In [ ]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [ ]:
# in case if you use all these together,
# the standard order of operations is respected:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy; for example, the `+` operator is a wrapper for the `add` function.
The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


### Absolute value
Just as NumPy understands Python's built-in arithmetic operators, it also understands Python's built-in absolute value function:

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [ ]:
np.abs(x)
np.absolute(x)

array([2, 1, 0, 1, 2])

### Trigonometric functions
NumPy provides a large number of useful ufuncs, and some of the most useful for the data scientist are the trigonometric functions. We'll start by defining an array of angles:

In [ ]:
theta = np.linspace(0, np.pi, 3)

[0.         1.57079633 3.14159265]


In [ ]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms
Another common type of operation available in a NumPy ufunc are the exponentials:

In [ ]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


The inverse of the exponentials, the logarithms, are also available. The basic np.log gives the natural logarithm; if you prefer to compute the base-2 logarithm or the base-10 logarithm, these are available as well:

In [ ]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


### Specifying output

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be. For all ufuncs, this can be done using the out argument of the function:

In [ ]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [ ]:
y = np.zeros(10)
y[::2] = np.power(3, x)
print(y)

[ 1.  0.  3.  0.  9.  0. 27.  0. 81.  0.]


If we had instead written `y[::2] = 2 ** x`, this would have resulted in the creation of a temporary array to hold the results of `2 ** x`, followed by a second operation copying those values into the y array.

In [ ]:
y = np.zeros(10)
np.power(3, x, out=y[::2])
print(y)

[ 1.  0.  3.  0.  9.  0. 27.  0. 81.  0.]


# Aggregations: Min, Max, and Everything In Between

Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question. Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the "typical" values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).

NumPy has fast built-in aggregation functions for working on arrays; we'll discuss and demonstrate some of them here.

## Sum

Let us consider computing the sum of all values in an array. Python itself can do this using the built-in sum function:

In [ ]:
L = np.random.random(100)
print("Python sum : ", sum(L))
print("NumPy sum : ", np.sum(L))

Python sum :  44.81684233959629
NumPy sum :  44.816842339596285


However, because it executes the operation in compiled code, NumPy's version of the operation is computed much more quickly:

In [ ]:
big_array = np.random.rand(1000000)
%time sum(big_array)
%time np.sum(big_array)

CPU times: user 176 ms, sys: 0 ns, total: 176 ms
Wall time: 177 ms
CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 969 µs


499764.5201551815

Be careful, though: the ``sum`` function and the ``np.sum`` function are not identical, which can sometimes lead to confusion!
In particular, their optional arguments have different meanings, and ``np.sum`` is aware of multiple array dimensions, as we will see in the following section.

## Minimum and Maximum
Similarly, Python has built-in `min` and `max` functions, used to find the minimum value and maximum value of any given array:

In [ ]:
min(big_array), max(big_array)

(4.844385737001744e-08, 0.9999995203964611)

In [ ]:
np.min(big_array), np.max(big_array)

(4.844385737001744e-08, 0.9999995203964611)

In [ ]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 3: 101 ms per loop
1000 loops, best of 3: 409 µs per loop


For ``min``, ``max``, ``sum``, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself:

In [ ]:
print(big_array.min(), big_array.max(), big_array.sum())

4.844385737001744e-08 0.9999995203964611 499764.5201551815


Whenever possible, make sure that you are using the NumPy version of these aggregates when operating on NumPy arrays!

## Multi dimensional aggregates
One common type of aggregation operation is an aggregate along a row or column. Say you have some data stored in a two-dimensional array:

In [ ]:
M = np.random.random((3, 4))
print(M)

[[0.5572068  0.56464233 0.42943773 0.32946457]
 [0.63432366 0.60177957 0.82191961 0.54604899]
 [0.53486178 0.88165557 0.16330887 0.08572345]]


By default, each NumPy aggregation function will return the aggregate over the entire array:

In [ ]:
M.sum() # np.sum(M)

6.150372922997595

Aggregation functions take an additional argument specifying the axis along which the aggregate is computed. For example, we can find the minimum/maximum value within each column by specifying **axis=0** and minimum/maximum value within each row by specifying **axis=1**:

In [ ]:
M.shape

(3, 4)

In [ ]:
print(M.min(axis=0))
print(M.min(axis=1))

[0.53486178 0.56464233 0.16330887 0.08572345]
[0.32946457 0.54604899 0.08572345]


In [ ]:
print(M.mean(axis=0))
print(M.sum(axis=1))

[0.57546408 0.68269249 0.4715554  0.32041234]
[1.88075143 2.60407182 1.66554967]


NumPy provides many other aggregation functions, but we won't discuss them in detail here. Additionally, most aggregates have a NaN-safe counterpart that computes the result while ignoring missing values, which are marked by the special IEEE floating-point NaN (acronym for Not a Number) value.

In [ ]:
vals = np.array([1, np.nan, 3, 4])
vals.dtype

dtype('float64')

In [ ]:
1 + np.nan

nan

In [ ]:
0 *  np.nan

nan

In [ ]:
vals.sum(), vals.min(), vals.max()

(nan, nan, nan)

In [ ]:
np.nansum(vals), np.nanmin(vals), np.nanmax(vals)

(8.0, 1.0, 4.0)

Keep in mind that NaN is specifically a floating-point value; there is no equivalent NaN value for integers, strings, or other types.

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |


In [1]:
# ==========================================
# NUMPY PRACTICE PROBLEMS / УПРАЖНЕНИЯ NUMPY
# ==========================================


# 1.
# EN: Create a NumPy array containing numbers from 1 to 20.
# Print:
#   a) the shape
#   b) the data type
#   c) the sum of all elements
#
# RU: Создайте массив NumPy, содержащий числа от 1 до 20.
# Выведите:
#   a) размерность массива
#   b) тип данных
#   c) сумму всех элементов


# 2.
# EN: Convert the following Python list into a NumPy array.
# Then multiply every element by 5 using vectorized operations.
#
# RU: Преобразуйте следующий список Python в массив NumPy.
# Затем умножьте каждый элемент на 5 с помощью векторизованных операций.
data = [2, 4, 6, 8, 10]


# 3.
# EN: Create a NumPy array of 15 equally spaced numbers between 0 and 3.
# Hint: use linspace().
#
# RU: Создайте массив NumPy из 15 равномерно распределённых чисел
# на интервале от 0 до 3.
# Подсказка: используйте функцию linspace().


# 4.
# EN: Generate a 4×4 matrix of random numbers between 0 and 1.
# Print:
#   a) the maximum value
#   b) the minimum value
#   c) the mean value
#
# RU: Сгенерируйте матрицу 4×4 из случайных чисел от 0 до 1.
# Выведите:
#   a) максимальное значение
#   b) минимальное значение
#   c) среднее значение


# 5.
# EN: Create a NumPy array:
#     [5, 10, 15, 20, 25, 30]
# Extract only the elements greater than 15 using boolean indexing.
#
# RU: Создайте массив NumPy:
#     [5, 10, 15, 20, 25, 30]
# Извлеките только элементы больше 15,
# используя булеву индексацию.


# 6.
# EN: Create a 5×5 matrix using arange().
# Reshape it so that the matrix contains numbers from 1 to 25.
#
# RU: Создайте матрицу 5×5 с помощью функции arange().
# Измените форму массива так, чтобы матрица
# содержала числа от 1 до 25.


# 7.
# EN: Using the matrix from the previous task:
#   a) extract the third row
#   b) extract the second column
#   c) extract the 2×2 block in the top-left corner
#
# RU: Используя матрицу из предыдущего задания:
#   a) извлеките третью строку
#   b) извлеките второй столбец
#   c) извлеките блок 2×2 в левом верхнем углу


# 8.
# EN: Create two arrays:
#   A = [1,2,3,4]
#   B = [10,20,30,40]
# Compute:
#   a) A + B
#   b) A * B
#   c) A ** 2
#
# RU: Создайте два массива:
#   A = [1,2,3,4]
#   B = [10,20,30,40]
# Вычислите:
#   a) A + B
#   b) A * B
#   c) A ** 2


# 9.
# EN: Generate an array with values from -5 to 5.
# Compute the following NumPy universal functions:
#   a) sin(x)
#   b) cos(x)
#   c) exp(x)
#
# RU: Сгенерируйте массив со значениями от -5 до 5.
# Вычислите следующие универсальные функции NumPy:
#   a) sin(x)
#   b) cos(x)
#   c) exp(x)


# 10.
# EN: Create a 3×3 matrix of random integers between 1 and 20.
# Compute:
#   a) row sums
#   b) column sums
#
# RU: Создайте матрицу 3×3 из случайных целых чисел
# от 1 до 20.
# Найдите:
#   a) суммы строк
#   b) суммы столбцов


# 11.
# EN: Demonstrate broadcasting:
# Create a 3×4 matrix of ones.
# Add the vector [1,2,3,4] to every row.
#
# RU: Продемонстрируйте broadcasting:
# Создайте матрицу 3×4 из единиц.
# Прибавьте вектор [1,2,3,4] к каждой строке.


# 12.
# EN: Generate an array of 1000 random numbers from a normal distribution.
# Compute:
#   a) mean
#   b) standard deviation
#   c) variance
#
# RU: Сгенерируйте массив из 1000 случайных чисел
# из нормального распределения.
# Найдите:
#   a) среднее значение
#   b) стандартное отклонение
#   c) дисперсию


# 13.
# EN: Create a NumPy array containing numbers from 1 to 50.
# Replace all numbers divisible by 5 with 0.
#
# RU: Создайте массив NumPy с числами от 1 до 50.
# Замените все числа, кратные 5, на 0.


# 14.
# EN: Create two random matrices of size 3×3.
# Compute their matrix multiplication using NumPy.
#
# RU: Создайте две случайные матрицы размером 3×3.
# Выполните их матричное умножение с помощью NumPy.


# 15.
# EN: Generate 100 evenly spaced points between -2 and 2.
# Evaluate the function:
#
#       f(x) = 1 / (1 + 25x^2)
#
# Store the result in another NumPy array.
#
# RU: Сгенерируйте 100 равномерно распределённых точек
# на интервале от -2 до 2.
# Вычислите функцию:
#
#       f(x) = 1 / (1 + 25x^2)
#
# Сохраните результат в другом массиве NumPy.

##### Create a NumPy array containing numbers from 1 to 20.  Print:  a) the shape  b) the data type  c) the sum of all elements


In [143]:
arr = np.arange(1, 21)

print("Shape:", arr.shape)

print("Data Type:", arr.dtype)

print("Sum:", arr.sum())

Shape: (20,)
Data Type: int32
Sum: 210


##### Convert the following Python list into a NumPy array. Then multiply every element by 5 using vectorized operations.

In [144]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
result = my_array * 5
print(result)


[ 5 10 15 20 25]


##### Create a NumPy array of 15 equally spaced numbers between 0 and 3. Hint: use linspace().


In [ ]:
arr = np.linspace(0, 3, 15)
print(arr)

[0.         0.21428571 0.42857143 0.64285714 0.85714286 1.07142857
 1.28571429 1.5        1.71428571 1.92857143 2.14285714 2.35714286
 2.57142857 2.78571429 3.        ]


 ##### Generate a 4×4 matrix of random numbers between 0 and 1. Print:  a) the maximum valu  b) the minimum value  c) the mean value

In [146]:
matrix = np.random.rand(4, 4)

print("Matrix:\n", matrix)
print("Maximum value:", matrix.max())
print("Minimum value:", matrix.min())
print("Mean value:", matrix.mean())

Matrix:
 [[0.90843763 0.03517113 0.23305833 0.08445344]
 [0.50803214 0.45287571 0.18508702 0.29471618]
 [0.26619231 0.19281174 0.29981223 0.86761945]
 [0.35081671 0.5487962  0.26253188 0.17609886]]
Maximum value: 0.9084376278391543
Minimum value: 0.035171130839614095
Mean value: 0.35415693508643153


##### Create a NumPy array:  [5, 10, 15, 20, 25, 30] Extract only the elements greater than 15 using boolean indexing.

In [21]:
arr = np.array([5, 10, 15, 20, 25, 30])

result = arr[arr > 15]
result

array([20, 25, 30])

##### Create a 5×5 matrix using arange(). Reshape it so that the matrix contains numbers from 1 to 25.

In [149]:
matrix = np.arange(1, 26).reshape(5, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### 7 Using the matrix from the previous task: a) extract the third row b) extract the second column c) extract the 2×2 block in the top-left corner

In [151]:
third_row = matrix[2, :]
second_column = matrix[:, 1]
top_left_block = matrix[0:2, 0:2]

print(third_column)
print(second_column)
print(top_left_block)

[ 3  7 11 15]
[ 2  7 12 17 22]
[[1 2]
 [6 7]]


##### Create two arrays: A = [1,2,3,4] B = [10,20,30,40] Compute: a) A + B b) A * B c) A ** 2

In [153]:
A = np.array([1,2,3,4])
B = np.array([10,20,30,40])

print(A + B)
print(A * B)
print(A ** 2)

[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]


##### Generate an array with values from -5 to 5. Compute the following NumPy universal functions: a) sin(x) b) cos(x) c) exp(x)

In [154]:
x = np.arange(-5, 6)

sine_values = np.sin(x)
cosine_values = np.cos(x)
exp_values = np.exp(x)

print(f"Array: {x}")
print(f"Sin: {sine_values}")
print(f"Cos: {cosine_values}")
print(f"Exp: {exp_values}")

Array: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Sin: [ 0.95892427  0.7568025  -0.14112001 -0.90929743 -0.84147098  0.
  0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos: [ 0.28366219 -0.65364362 -0.9899925  -0.41614684  0.54030231  1.
  0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Exp: [6.73794700e-03 1.83156389e-02 4.97870684e-02 1.35335283e-01
 3.67879441e-01 1.00000000e+00 2.71828183e+00 7.38905610e+00
 2.00855369e+01 5.45981500e+01 1.48413159e+02]


##### EN: Create a 3×3 matrix of random integers between 1 and 20. Compute: a) row sums b) column sums

In [2]:
import numpy as np

In [3]:
matrix = np.random.randint(1, 21, size=(3, 3))

# row sums
row_sums = matrix.sum(axis=1)

# column sums
col_sums = matrix.sum(axis=0)

print("Matrix:\n", matrix)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Matrix:
 [[20 16 16]
 [17 14 15]
 [11  2  9]]
Row sums: [52 46 22]
Column sums: [48 32 40]


##### 11. Demonstrate broadcasting: Create a 3×4 matrix of ones. Add the vector [1,2,3,4] to every row.

In [4]:

matrix = np.ones((3, 4))
print("Original Matrix (3x4):\n", matrix)

vector = np.array([1, 2, 3, 4])

result = matrix + vector

print("\nResulting Matrix after broadcasting:\n", result)

Original Matrix (3x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Resulting Matrix after broadcasting:
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


##### EN: Generate an array of 1000 random numbers from a normal distribution. Compute: a) mean b) standard deviation c) variance

In [8]:
data = np.random.normal(0, 1, 1000)

mean = data.mean()
std_dev = data.std()
variance = data.var()

print(f"Mean: {mean}")
print(f"Standard Deviation: {std_dev}")
print(f"Variance: {variance}")

Mean: 0.013626815141802445
Standard Deviation: 0.9820006363776017
Variance: 0.9643252498460148


##### Create a NumPy array containing numbers from 1 to 50. Replace all numbers divisible by 5 with 0.

In [15]:
matrix = np.random.randint(1, 50, size=(5,5))
print(f"the original matrix\n {matrix}")
matrix[matrix % 5 == 0] = 0
matrix

the original matrix
 [[34 27 20 46 37]
 [31  9 12 30  6]
 [36 37 10 22 40]
 [ 7  1 35  4 14]
 [48 47  9 33 15]]


array([[34, 27,  0, 46, 37],
       [31,  9, 12,  0,  6],
       [36, 37,  0, 22,  0],
       [ 7,  1,  0,  4, 14],
       [48, 47,  9, 33,  0]], dtype=int32)

##### Create two random matrices of size 3×3. Compute their matrix multiplication using NumPy.


In [16]:
matrix1 = np.random.randint(1,100, size=(2,3))
matrix2 = np.random.randint(1,100, size=(3,2))
mult = matrix1.dot(matrix2)
mult

array([[ 7884,  7860],
       [10567,  9246]], dtype=int32)

##### Generate 100 evenly spaced points between -2 and 2. Evaluate the function: f(x) = 1 / (1 + 25x^2) Store the result in another NumPy array.

In [ ]:
x = np.linspace(-2, 2, 100)
print(x)
y = 1 / (1 + 25 * x**2)
print(y)

[-2.         -1.95959596 -1.91919192 -1.87878788 -1.83838384 -1.7979798
 -1.75757576 -1.71717172 -1.67676768 -1.63636364 -1.5959596  -1.55555556
 -1.51515152 -1.47474747 -1.43434343 -1.39393939 -1.35353535 -1.31313131
 -1.27272727 -1.23232323 -1.19191919 -1.15151515 -1.11111111 -1.07070707
 -1.03030303 -0.98989899 -0.94949495 -0.90909091 -0.86868687 -0.82828283
 -0.78787879 -0.74747475 -0.70707071 -0.66666667 -0.62626263 -0.58585859
 -0.54545455 -0.50505051 -0.46464646 -0.42424242 -0.38383838 -0.34343434
 -0.3030303  -0.26262626 -0.22222222 -0.18181818 -0.14141414 -0.1010101
 -0.06060606 -0.02020202  0.02020202  0.06060606  0.1010101   0.14141414
  0.18181818  0.22222222  0.26262626  0.3030303   0.34343434  0.38383838
  0.42424242  0.46464646  0.50505051  0.54545455  0.58585859  0.62626263
  0.66666667  0.70707071  0.74747475  0.78787879  0.82828283  0.86868687
  0.90909091  0.94949495  0.98989899  1.03030303  1.07070707  1.11111111
  1.15151515  1.19191919  1.23232323  1.27272727  1.3

array([0.00990099, 0.01030923, 0.01074316, 0.01120497, 0.01169709,
       0.01222221, 0.01278334, 0.01338384, 0.01402746, 0.0147184 ,
       0.0154614 , 0.01626179, 0.0171256 , 0.01805967, 0.01907177,
       0.02017078, 0.02136686, 0.0226717 , 0.02409879, 0.02566372,
       0.02738467, 0.02928285, 0.03138318, 0.03371505, 0.03631331,
       0.03921953, 0.04248356, 0.04616559, 0.05033872, 0.05509244,
       0.06053699, 0.06680936, 0.07408107, 0.08256881, 0.0925487 ,
       0.10437589, 0.11851126, 0.13555829, 0.1563133 , 0.18183336,
       0.21352476, 0.25324927, 0.30342714, 0.3670649 , 0.44751381,
       0.54751131, 0.66668934, 0.79676449, 0.91589571, 0.98990001,
       0.98990001, 0.91589571, 0.79676449, 0.66668934, 0.54751131,
       0.44751381, 0.3670649 , 0.30342714, 0.25324927, 0.21352476,
       0.18183336, 0.1563133 , 0.13555829, 0.11851126, 0.10437589,
       0.0925487 , 0.08256881, 0.07408107, 0.06680936, 0.06053699,
       0.05509244, 0.05033872, 0.04616559, 0.04248356, 0.03921